GET http://localhost:3010/titles/

#######
GET http://localhost:3010/titles/query/?type=Movie&title=23:59&country=

#######

GET http://localhost:3010/titles/actor/?cast=Samuel+L.+Jackson

#######

GET http://localhost:3010/titles/stats/?type=Movie&release_year=&country=Mexico